### ISSUE TITLE
new pp record, `user/mrekk.md` is affected.

### ISSUE THREAD

**Issue by WindowsMeosu** [WindowsMeosu/peppypedia#64]
whyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by WindowsMeosu** [comment]
todo: create `user/akolibed`. (pp records were the worst thing to be invented)

**Comment by p0s0** [comment]
yo i got some bad news bro

**Comment by WindowsMeosu** [comment]
> yo i got some bad news bro

i'm aware... unfortunately

**Comment by WindowsMeosu** [comment]
not sure why this is still open
