### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by trep744** [WindowsMeosu/peppypedia#73]
heyo @WindowsMeosu (i've never used github so i hope i'm posting in this the right placee), i've been visiting your site pretty often noww. I'm unsureee  if  this is an  issue  or not on https://milotilo.ddns.net/peppypedia/content/en/medals/Jackpot.html the footnote below doesn't  link  to anythinggg...

**Comment by WindowsMeosu** [comment]
yeah i was aware of that
