### ISSUE TITLE
show player's rraank

### ISSUE THREAD

**Issue by trep744** [WindowsMeosu/peppypedia#75]

**Comment by trep744** [comment]
howw   doo ii edit???/

**Comment by trep744** [comment]
basicalllyyyy shows the plaayerss rank on the page, for mrekk it'd be #1

**Comment by WindowsMeosu** [comment]
So, If I'm understanding you correctly, include the user's current - Performance Points - rank alongside the country rank?... Manually, no. If anything I'd do it by calling requests to osu!'s api and write the rank with it. However, github pages doesn't really handle cross site requests very well. Closed, for now.

**Comment by WindowsMeosu** [comment]
Changed my mind - not possible.
